name: Daily Commit Automation

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:  # allows manual trigger

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add a commit (email: 24f2001361@ds.study.iitm.ac.in)
        run: |
          git config --local user.name "GitHub Action Bot"
          git config --local user.email "24f2001361@ds.study.iitm.ac.in"
          echo "Last run: $(date -u)" > daily-update.txt
          git add daily-update.txt
          git commit -m "Daily commit [skip ci]" || echo "No changes to commit"
          git push
